### ISSUE TITLE
Generated migration invalid due to default value of datetime column

### ISSUE THREAD

**Issue by dgmdan** [liaan/codeigniter_migration_base_generation#1]
I have a table in my DB with this schema:

``` sql
CREATE TABLE IF NOT EXISTS `dm_ad_groups` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
```

When I used this library, I found that the migration was generated like this:

``` php
 $this->dbforge->add_field("`id` int(11) unsigned NOT NULL auto_increment");
 $this->dbforge->add_key("id",true);
 $this->dbforge->add_field("`name` varchar(255) NOT NULL ");
 $this->dbforge->add_field("`created` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' ");
 $this->dbforge->create_table("dm_ad_groups", TRUE);
```

This gives me an error when I try to run it:

```
 <p>Error Number: 1067</p><p>Invalid default value for 'created'</p>
```

Could you please fix this?  I was able to work around it by manually removing the single quotes around CURRENT_TIMESTAMP in the generated migration.

**Comment by liaan** [comment]
Hi, 

Will check it out.. 

thanks
L:

**Comment by liaan** [comment]
@dgmdan 

I did quick hack for this also added table engine check to make sure you keep correct table engine..

L:

**Comment by dgmdan** [comment]
Thanks.  It didn't work but I figured out how to fix it and will open a PR now.
