### ISSUE TITLE
also need a method to migrate data

### ISSUE THREAD

**Issue by singleseeker** [liaan/codeigniter_migration_base_generation#5]
sometimes we also need both structure and data.

**Comment by liaan** [comment]
Hi @singleseeker , 

Not 100% sure what you want the data migration for, can you please elaborate?

L:

**Comment by singleseeker** [comment]
what i said is just hope there will be a method allow us to dump data from mysql.

**Comment by liaan** [comment]
Hi, You can use the build in CI backup utility, only works for mysql (not mysqli).
I have library for the mysqli drivers if you need that .

L:
