### ISSUE TITLE
Incorrect table definition; there can be only one auto column and it must be defined as a key

### ISSUE THREAD

**Issue by joao-gabriel** [liaan/codeigniter_migration_base_generation#6]
Hello, 

I keep getting this error when trying to execute migrations that creates more than one table :

```
A Database Error Occurred

Error Number: 1075

Incorrect table definition; there can be only one auto column and it must be defined as a key

CREATE TABLE IF NOT EXISTS `categories` ( `id` int(11) unsigned NOT NULL auto_increment, `parent_id` int(11) NULL , `name` varchar(255) NOT NULL , `color` varchar(7) NOT NULL DEFAULT '#000000' ) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci

Filename: migrations/001_create_base.php

Line Number: 13
```

Here is the code inside method up() generated by your tool:

```
		## Create Table categories
		$this->dbforge->add_field("`id` int(11) unsigned NOT NULL auto_increment");
		$this->dbforge->add_key("id",true);
		$this->dbforge->add_field("`parent_id` int(11) NULL ");
		$this->dbforge->add_field("`name` varchar(255) NOT NULL ");
		$this->dbforge->add_field("`color` varchar(7) NOT NULL DEFAULT '#000000' ");
		$this->dbforge->create_table("categories", TRUE);
		$this->db->query('ALTER TABLE  `categories` ENGINE = InnoDB');
		## Create Table categories_entries
		$this->dbforge->add_field("`id` int(11) unsigned NOT NULL auto_increment");
		$this->dbforge->add_key("id",true);
		$this->dbforge->add_field("`category_id` int(11) unsigned NOT NULL ");
		$this->dbforge->add_field("`entry_id` int(11) unsigned NOT NULL ");
		$this->dbforge->create_table("categories_entries", TRUE);
		$this->db->query('ALTER TABLE  `categories_entries` ENGINE = `InnoDB');
		## Create Table entries
		$this->dbforge->add_field("`id` int(11) unsigned NOT NULL auto_increment");
		$this->dbforge->add_key("id",true);
		$this->dbforge->add_field("`name` varchar(255) NOT NULL ");
		$this->dbforge->add_field("`income` tinyint(1) NOT NULL ");
		$this->dbforge->add_field("`value` decimal(9,2) NOT NULL ");
		$this->dbforge->add_field("`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ");
		$this->dbforge->add_field("`modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP");
		$this->dbforge->create_table("entries", TRUE);
		$this->db->query('ALTER TABLE  `entries` ENGINE = InnoDB');
```

I may be wrong but it seems dbforge doesn't "reset" after the creation of the first table, and consider two auto_increment fields in the same table.

Thanks in advance!

**Comment by chakan** [comment]
Hi there,

As far as I can see DBForge handles "id" fields as "special exceptions". When you create an "id" field it has type automatically assigned, and that seems to have a conflict with the explicit definition.

`$this->dbforge->add_field('id');
// gives id INT(9) NOT NULL AUTO_INCREMENT`

A possible fix for this would be, that in the library when you iterate over the columns you check the field name. If it's "id" then set it with the method above. The downside would be that your "id" fields will need to be INT(9) when doing this.

**Comment by joao-gabriel** [comment]
Thanks for your answer. I've managed to make it work by using one dbForge instance per table:

$table1 = $this->load->dbForge(NULL, TRUE);
$table1->add_field('id')->create_table('table1');

$table2 = $this->load->dbForge(NULL, TRUE);
$table2->add_field('id')->create_table('table2');

Maybe you should adapt the code to work this way when there's more than one table to be created.

Cheers!

**Comment by liaan** [comment]
Phew.. not checked github in ages .. closing this issue, please log another if still a problem
